//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adwiseus.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adwiseus.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pronto más información sobre Adwise University.
        /// </summary>
        public static string adwise_title {
            get {
                return ResourceManager.GetString("adwise_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicate con nosotros.
        /// </summary>
        public static string contacto_form_button {
            get {
                return ResourceManager.GetString("contacto_form_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string contacto_form_email {
            get {
                return ResourceManager.GetString("contacto_form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        public static string contacto_form_message {
            get {
                return ResourceManager.GetString("contacto_form_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string contacto_form_name {
            get {
                return ResourceManager.GetString("contacto_form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Gracias por visitar la página de Adwise Corporate Advisory!.
        /// </summary>
        public static string contacto_p1 {
            get {
                return ResourceManager.GetString("contacto_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +1 786-220-3758.
        /// </summary>
        public static string contacto_p10 {
            get {
                return ResourceManager.GetString("contacto_p10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperamos tener la oportunidad de trabajar contigo y ayudarte a alcanzar tus objetivos empresariales. ¡Contáctanos hoy mismo!.
        /// </summary>
        public static string contacto_p11 {
            get {
                return ResourceManager.GetString("contacto_p11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En Adwise Corporate Advisory estamos comprometidos con brindar un excelente servicio al cliente y una asesoría de primera calidad. Si tienes alguna pregunta, inquietud o comentario, no dudes en ponerte en contacto con nosotros..
        /// </summary>
        public static string contacto_p2 {
            get {
                return ResourceManager.GetString("contacto_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para hacerlo, puedes completar el formulario de contacto que se encuentra en nuestra página web. Simplemente ingresa tu nombre, dirección de correo electrónico y un mensaje detallado, y uno de nuestros expertos en asesoramiento corporativo te responderá lo antes posible..
        /// </summary>
        public static string contacto_p3 {
            get {
                return ResourceManager.GetString("contacto_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a También puedes comunicarte con nosotros a través de nuestros números telefónicos..
        /// </summary>
        public static string contacto_p4 {
            get {
                return ResourceManager.GetString("contacto_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a San José, Costa Rica.
        /// </summary>
        public static string contacto_p5 {
            get {
                return ResourceManager.GetString("contacto_p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +506 61264151.
        /// </summary>
        public static string contacto_p6 {
            get {
                return ResourceManager.GetString("contacto_p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad de Panamá, Panamá.
        /// </summary>
        public static string contacto_p7 {
            get {
                return ResourceManager.GetString("contacto_p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +507 63062254.
        /// </summary>
        public static string contacto_p8 {
            get {
                return ResourceManager.GetString("contacto_p8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miami, FL. USA.
        /// </summary>
        public static string contacto_p9 {
            get {
                return ResourceManager.GetString("contacto_p9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, ha ocurrido un error al enviar tu mensaje. Por favor, inténtalo de nuevo más tarde o contáctanos directamente a través de nuestro correo electrónico.
        /// </summary>
        public static string contacto_rta_error {
            get {
                return ResourceManager.GetString("contacto_rta_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tu mensaje ha sido enviado con éxito!.
        /// </summary>
        public static string contacto_rta_exito_h2 {
            get {
                return ResourceManager.GetString("contacto_rta_exito_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string contacto_rta_exito_li1 {
            get {
                return ResourceManager.GetString("contacto_rta_exito_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        public static string contacto_rta_exito_li2 {
            get {
                return ResourceManager.GetString("contacto_rta_exito_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje:.
        /// </summary>
        public static string contacto_rta_exito_li3 {
            get {
                return ResourceManager.GetString("contacto_rta_exito_li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A continuación, se muestran los detalles del mensaje:.
        /// </summary>
        public static string contacto_rta_exito_p {
            get {
                return ResourceManager.GetString("contacto_rta_exito_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Son áreas esenciales de la gestión empresarial encargadas de la gestión financiera, el control financiero y la evaluación independiente de la situación financiera de una empresa. Las finanzas incluyen la planificación financiera, la gestión de presupuestos y tesorería, la inversión y financiación, y la preparación de informes financieros, mientras que la auditoría se enfoca en la revisión y evaluación independiente de los estados financieros de la empresa. Ambas áreas son fundamentales para garantizar la so [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string finance_descr {
            get {
                return ResourceManager.GetString("finance_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finance Audit.
        /// </summary>
        public static string finance_h1 {
            get {
                return ResourceManager.GetString("finance_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resources Management Insights.
        /// </summary>
        public static string finance_h2_1 {
            get {
                return ResourceManager.GetString("finance_h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audit Best Practices.
        /// </summary>
        public static string finance_h2_2 {
            get {
                return ResourceManager.GetString("finance_h2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financial Information Management.
        /// </summary>
        public static string finance_h2_3 {
            get {
                return ResourceManager.GetString("finance_h2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expertise Delivery Center.
        /// </summary>
        public static string finance_h2_4 {
            get {
                return ResourceManager.GetString("finance_h2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compliance Analysis Review.
        /// </summary>
        public static string finance_h2_5 {
            get {
                return ResourceManager.GetString("finance_h2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios integrados en asesoría financiera y contable enfocados en el mejoramiento de la gestión financiera.
        /// </summary>
        public static string finance_p_1 {
            get {
                return ResourceManager.GetString("finance_p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metodologías para la evaluación independiente y sistemática de la información y los procesos financieros y administrativos.
        /// </summary>
        public static string finance_p_2 {
            get {
                return ResourceManager.GetString("finance_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistemas de integración, consolidación y de la información financiera para múltiples negocios, contables y territoriales.
        /// </summary>
        public static string finance_p_3 {
            get {
                return ResourceManager.GetString("finance_p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estrategias para la innovación y optimización de los recursos y procesos comunes, afianzando la efectividad y competitividad operativa.
        /// </summary>
        public static string finance_p_4 {
            get {
                return ResourceManager.GetString("finance_p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programas para la evaluación especializada del cumplimiento de disposiciones específicas y la efectividad del sistema de control interno.
        /// </summary>
        public static string finance_p_5 {
            get {
                return ResourceManager.GetString("finance_p_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a más información.
        /// </summary>
        public static string index_buttonHeader {
            get {
                return ResourceManager.GetString("index_buttonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ver mas.
        /// </summary>
        public static string index_buttonText {
            get {
                return ResourceManager.GetString("index_buttonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Como empresa de consultoría, nos enfocamos en ofrecer soluciones innovadoras y personalizadas para ayudar a nuestros clientes a alcanzar sus objetivos comerciales. Aquí presentamos algunos de nuestros casos de éxito más destacados..
        /// </summary>
        public static string index_card1Content {
            get {
                return ResourceManager.GetString("index_card1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        public static string index_card1Title {
            get {
                return ResourceManager.GetString("index_card1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adwise University es un Centro de Formación de Alto Nivel Ejecutivo que ofrece una oferta académica enfocada en la implementación exitosa de la Transformación Digital en Gobiernos, Entidades Financieras y Organismos de Cooperación Internacional. Con nosotros obtendrás una formación de alta calidad para liderar el cambio hacia un futuro más digital y eficiente en tu organización..
        /// </summary>
        public static string index_card2Content {
            get {
                return ResourceManager.GetString("index_card2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adwise University.
        /// </summary>
        public static string index_card2Title {
            get {
                return ResourceManager.GetString("index_card2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultoría especializada en Educación, Gestión del Capital Humano, Innovación, Desarrollo Organizacional, Gestión del Cambio, Tercerización y Programas para el Desarrollo del Talento.
        /// </summary>
        public static string index_PHeader {
            get {
                return ResourceManager.GetString("index_PHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adwise se especializa en diferentes áreas de negocio, entre las que se incluyen la gestión del talento, la innovación de procesos, las finanzas y la auditoría, y el outsourcing. Cada una de estas áreas es importante para el éxito y la competitividad a largo plazo de una empresa..
        /// </summary>
        public static string indexArea_descr {
            get {
                return ResourceManager.GetString("indexArea_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Áreas De Especialidad.
        /// </summary>
        public static string indexArea_h1 {
            get {
                return ResourceManager.GetString("indexArea_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talent Management.
        /// </summary>
        public static string indexArea_h2_1 {
            get {
                return ResourceManager.GetString("indexArea_h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process Innovation.
        /// </summary>
        public static string indexArea_h2_2 {
            get {
                return ResourceManager.GetString("indexArea_h2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finance&amp;Audit.
        /// </summary>
        public static string indexArea_h2_3 {
            get {
                return ResourceManager.GetString("indexArea_h2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outsourcing.
        /// </summary>
        public static string indexArea_h2_4 {
            get {
                return ResourceManager.GetString("indexArea_h2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se enfoca en atraer, desarrollar, motivar y retener a empleados altamente calificados y comprometidos para contribuir al éxito de la empresa..
        /// </summary>
        public static string indexArea_p_1 {
            get {
                return ResourceManager.GetString("indexArea_p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se refiere a la mejora de procesos empresariales para aumentar la eficiencia, productividad y calidad de los productos o servicios ofrecidos..
        /// </summary>
        public static string indexArea_p_2 {
            get {
                return ResourceManager.GetString("indexArea_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las finanzas y la auditoría son fundamentales para garantizar la sostenibilidad y salud financiera de la empresa..
        /// </summary>
        public static string indexArea_p_3 {
            get {
                return ResourceManager.GetString("indexArea_p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se utiliza para reducir costos, mejorar la eficiencia y acceder a habilidades especializadas..
        /// </summary>
        public static string indexArea_p_4 {
            get {
                return ResourceManager.GetString("indexArea_p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Áreas de Especialidad.
        /// </summary>
        public static string nav_areas {
            get {
                return ResourceManager.GetString("nav_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string nav_contacto {
            get {
                return ResourceManager.GetString("nav_contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string nav_inicio {
            get {
                return ResourceManager.GetString("nav_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nosotros.
        /// </summary>
        public static string nav_nosotros {
            get {
                return ResourceManager.GetString("nav_nosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfiles.
        /// </summary>
        public static string nav_perfiles {
            get {
                return ResourceManager.GetString("nav_perfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CEO.
        /// </summary>
        public static string nosotros_CEO {
            get {
                return ResourceManager.GetString("nosotros_CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es buscar el crecimiento como personas y como profesionales..
        /// </summary>
        public static string nosotros_crecimiento_li1 {
            get {
                return ResourceManager.GetString("nosotros_crecimiento_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es generar un ambiente laboral que permita sentirnos felices y realizados en cada día de trabajo..
        /// </summary>
        public static string nosotros_crecimiento_li2 {
            get {
                return ResourceManager.GetString("nosotros_crecimiento_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica mejorar continuamente las condiciones laborales..
        /// </summary>
        public static string nosotros_crecimiento_li3 {
            get {
                return ResourceManager.GetString("nosotros_crecimiento_li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica estar comprometidos..
        /// </summary>
        public static string nosotros_crecimiento_li4 {
            get {
                return ResourceManager.GetString("nosotros_crecimiento_li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRECIMIENTO PERSONAL.
        /// </summary>
        public static string nosotros_crecimiento_title {
            get {
                return ResourceManager.GetString("nosotros_crecimiento_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es hacer que las cosas sucedan..
        /// </summary>
        public static string nosotros_ejecucion_li1 {
            get {
                return ResourceManager.GetString("nosotros_ejecucion_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es ir siempre un paso más allá..
        /// </summary>
        public static string nosotros_ejecucion_li2 {
            get {
                return ResourceManager.GetString("nosotros_ejecucion_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica estar enfocados en el cliente..
        /// </summary>
        public static string nosotros_ejecucion_li3 {
            get {
                return ResourceManager.GetString("nosotros_ejecucion_li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica ser efectivos..
        /// </summary>
        public static string nosotros_ejecucion_li4 {
            get {
                return ResourceManager.GetString("nosotros_ejecucion_li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica estar comprometidos..
        /// </summary>
        public static string nosotros_ejecucion_li5 {
            get {
                return ResourceManager.GetString("nosotros_ejecucion_li5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EJECUCIÓN.
        /// </summary>
        public static string nosotros_ejecucion_title {
            get {
                return ResourceManager.GetString("nosotros_ejecucion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es hacer las cosas bien desde la primera vez..
        /// </summary>
        public static string nosotros_excelencia_li1 {
            get {
                return ResourceManager.GetString("nosotros_excelencia_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica trabajo en equipo..
        /// </summary>
        public static string nosotros_excelencia_li2 {
            get {
                return ResourceManager.GetString("nosotros_excelencia_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica ser eficientes..
        /// </summary>
        public static string nosotros_excelencia_li3 {
            get {
                return ResourceManager.GetString("nosotros_excelencia_li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica superar las expectativas del cliente..
        /// </summary>
        public static string nosotros_excelencia_li4 {
            get {
                return ResourceManager.GetString("nosotros_excelencia_li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica estar comprometidos..
        /// </summary>
        public static string nosotros_excelencia_li5 {
            get {
                return ResourceManager.GetString("nosotros_excelencia_li5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXCELENCIA.
        /// </summary>
        public static string nosotros_excelencia_title {
            get {
                return ResourceManager.GetString("nosotros_excelencia_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max Santamaría Gutiérrez es el CEO y Senior Partner de ADWISE Corporate Advisory para Latinoamérica, con más de 20 años de experiencia en el mercado, es psicólogo graduado de la Universidad de Costa Rica y ha obtenido especializaciones en Negociación, Entrenamiento en Educación para el Desarrollo Humano y Asesoramiento Internacional en Psicología de los Procesos Grupales..
        /// </summary>
        public static string nosotros_Max1 {
            get {
                return ResourceManager.GetString("nosotros_Max1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha desarrollado investigaciones en áreas como Artificial Intelligence, Human Resources Scorecard, Desarrollo Corporativo, Transformación Digital, Leadership Awareness, Inteligencia Emocional, Sistemas de Gestión para la Productividad y Programación Neurolingüística en las organizaciones..
        /// </summary>
        public static string nosotros_Max2 {
            get {
                return ResourceManager.GetString("nosotros_Max2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha trabajado como consultor en América Latina para empresas de diferentes rubros y clústeres de negocio, incluyendo consumo masivo, petróleo, empaque, agroindustria, servicios, banca, tecnología, construcción, manufactura, exportación, seguridad, trading, ONG´s, desarrollo inmobiliario y muchas otras..
        /// </summary>
        public static string nosotros_Max3 {
            get {
                return ResourceManager.GetString("nosotros_Max3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveemos soluciones integrales de asesoría en negocios con enfoque en rentabilidad..
        /// </summary>
        public static string nosotros_mision_descr {
            get {
                return ResourceManager.GetString("nosotros_mision_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misión.
        /// </summary>
        public static string nosotros_mision_title {
            get {
                return ResourceManager.GetString("nosotros_mision_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Conoce más sobre nuestros proyectos&quot;.
        /// </summary>
        public static string nosotros_p_moreProyects {
            get {
                return ResourceManager.GetString("nosotros_p_moreProyects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es enfocarse en resultados y no en actividades..
        /// </summary>
        public static string nosotros_rentabilidad_li1 {
            get {
                return ResourceManager.GetString("nosotros_rentabilidad_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es ser efectivos y eficientes..
        /// </summary>
        public static string nosotros_rentabilidad_li2 {
            get {
                return ResourceManager.GetString("nosotros_rentabilidad_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es hacer más con la menor cantidad de recursos..
        /// </summary>
        public static string nosotros_rentabilidad_li3 {
            get {
                return ResourceManager.GetString("nosotros_rentabilidad_li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica estar comprometidos..
        /// </summary>
        public static string nosotros_rentabilidad_li4 {
            get {
                return ResourceManager.GetString("nosotros_rentabilidad_li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RENTABILIDAD.
        /// </summary>
        public static string nosotros_rentabilidad_title {
            get {
                return ResourceManager.GetString("nosotros_rentabilidad_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESPONSABILIDAD SOCIAL CORPORATIVA.
        /// </summary>
        public static string nosotros_responsabilidad_h1 {
            get {
                return ResourceManager.GetString("nosotros_responsabilidad_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fundación de Adwise.
        /// </summary>
        public static string nosotros_timeline_1 {
            get {
                return ResourceManager.GetString("nosotros_timeline_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ampliación de soluciones.
        /// </summary>
        public static string nosotros_timeline_2 {
            get {
                return ResourceManager.GetString("nosotros_timeline_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transnacionales en Centroamérica y el Caribe.
        /// </summary>
        public static string nosotros_timeline_3 {
            get {
                return ResourceManager.GetString("nosotros_timeline_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursal en Bogotá, Colombia.
        /// </summary>
        public static string nosotros_timeline_4 {
            get {
                return ResourceManager.GetString("nosotros_timeline_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevos consultores y directores.
        /// </summary>
        public static string nosotros_timeline_5 {
            get {
                return ResourceManager.GetString("nosotros_timeline_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca Adwise.
        /// </summary>
        public static string nosotros_timeline_6 {
            get {
                return ResourceManager.GetString("nosotros_timeline_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidación de unidad de outsourcing.
        /// </summary>
        public static string nosotros_timeline_7 {
            get {
                return ResourceManager.GetString("nosotros_timeline_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casa Matriz.
        /// </summary>
        public static string nosotros_timeline_8 {
            get {
                return ResourceManager.GetString("nosotros_timeline_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ver más.
        /// </summary>
        public static string nosotros_timeline_button {
            get {
                return ResourceManager.GetString("nosotros_timeline_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nosotros.
        /// </summary>
        public static string nosotros_Title {
            get {
                return ResourceManager.GetString("nosotros_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de la Empresa.
        /// </summary>
        public static string nosotros_Title2 {
            get {
                return ResourceManager.GetString("nosotros_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es ser éticos y leales con nuestros clientes, colaboradores, proveedores, aliados y con nuestra empresa..
        /// </summary>
        public static string nosotros_transparencia_li1 {
            get {
                return ResourceManager.GetString("nosotros_transparencia_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica comunicación abierta entre colaboradores..
        /// </summary>
        public static string nosotros_transparencia_li2 {
            get {
                return ResourceManager.GetString("nosotros_transparencia_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implica estar comprometidos..
        /// </summary>
        public static string nosotros_transparencia_li3 {
            get {
                return ResourceManager.GetString("nosotros_transparencia_li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRANSPARENCIA.
        /// </summary>
        public static string nosotros_transparencia_title {
            get {
                return ResourceManager.GetString("nosotros_transparencia_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seremos los principales aliados estratégicos de nuestros clientes..
        /// </summary>
        public static string nosotros_vision_descr {
            get {
                return ResourceManager.GetString("nosotros_vision_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visión.
        /// </summary>
        public static string nosotros_vision_title {
            get {
                return ResourceManager.GetString("nosotros_vision_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es la contratación de una empresa externa para realizar tareas o funciones empresariales que normalmente se llevan a cabo dentro de la organización. Se puede aplicar a una amplia gama de áreas, como contabilidad, marketing, soporte técnico y gestión de recursos humanos. Las empresas lo usan para reducir costos, mejorar la eficiencia y acceder a habilidades especializadas. Sin embargo, también puede haber desventajas, como la pérdida de control y la falta de calidad del trabajo. En general, el outsourcing es [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string outsourcing_descr {
            get {
                return ResourceManager.GetString("outsourcing_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outsourcing.
        /// </summary>
        public static string outsourcing_h1 {
            get {
                return ResourceManager.GetString("outsourcing_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talent Workforce Outsourcing.
        /// </summary>
        public static string outsourcing_h2_1 {
            get {
                return ResourceManager.GetString("outsourcing_h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information Tech &amp; Mobile Development.
        /// </summary>
        public static string outsourcing_h2_2 {
            get {
                return ResourceManager.GetString("outsourcing_h2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payroll Management.
        /// </summary>
        public static string outsourcing_h2_3 {
            get {
                return ResourceManager.GetString("outsourcing_h2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Smart Process Outsourcing.
        /// </summary>
        public static string outsourcing_h2_4 {
            get {
                return ResourceManager.GetString("outsourcing_h2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn Key Deriverables.
        /// </summary>
        public static string outsourcing_h2_5 {
            get {
                return ResourceManager.GetString("outsourcing_h2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios de tercerización de personal, temporal o permanente.
        /// </summary>
        public static string outsourcing_p_1 {
            get {
                return ResourceManager.GetString("outsourcing_p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de aplicaciones tecnológicas de última generación para la productividad.
        /// </summary>
        public static string outsourcing_p_2 {
            get {
                return ResourceManager.GetString("outsourcing_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesamiento administrativo y atención de clientes en nóminas tercerizadas.
        /// </summary>
        public static string outsourcing_p_3 {
            get {
                return ResourceManager.GetString("outsourcing_p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios de administración y ejecución de funciones no medulares para el negocio de nuestros clientes.
        /// </summary>
        public static string outsourcing_p_4 {
            get {
                return ResourceManager.GetString("outsourcing_p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solución que asegura entregables de paquete completo » end to end» de conformidad con un Acuerdo de Nivel de Servicio.
        /// </summary>
        public static string outsourcing_p_5 {
            get {
                return ResourceManager.GetString("outsourcing_p_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string perfiles_clients_h2 {
            get {
                return ResourceManager.GetString("perfiles_clients_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenidos a nuestra sección donde mostramos algunos de nuestros proyectos. Aquí presentamos algunos de nuestros casos de éxito más destacados. Como empresa de consultoría, nos enfocamos en ofrecer soluciones innovadoras y personalizadas para ayudar a nuestros clientes a alcanzar sus objetivos comerciales. Nuestro equipo altamente capacitado está comprometido en brindar resultados excepcionales y satisfacción al cliente..
        /// </summary>
        public static string perfiles_descr {
            get {
                return ResourceManager.GetString("perfiles_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        public static string perfiles_h1 {
            get {
                return ResourceManager.GetString("perfiles_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto BAC SANJOSE.
        /// </summary>
        public static string perfiles_proyecto_1 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionar el reclutamiento y entrenamiento de 100 Ejecutivos Senior de Servicios..
        /// </summary>
        public static string perfiles_proyecto_1_li1 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_1_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de 3 meses..
        /// </summary>
        public static string perfiles_proyecto_1_li2 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_1_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto PIZZA HUT CR.
        /// </summary>
        public static string perfiles_proyecto_2 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahorros de $250.000 en el macroproceso de Cadena de Abastecimiento (logística – comercial)..
        /// </summary>
        public static string perfiles_proyecto_2_li1 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_2_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de 6 meses..
        /// </summary>
        public static string perfiles_proyecto_2_li2 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_2_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto TETRA PAK SOUTHERN CONE.
        /// </summary>
        public static string perfiles_proyecto_3 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transformación de la Estrategia Comercial en proceso de integración de Argentina, Chile &amp; Uruguay..
        /// </summary>
        public static string perfiles_proyecto_3_li1 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_3_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de 1 año..
        /// </summary>
        public static string perfiles_proyecto_3_li2 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_3_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto KATTAN GROUP.
        /// </summary>
        public static string perfiles_proyecto_4 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estrategia de Alineamiento y Gestión de Capital Humano de para grupo empresarial de 4.000 empleados en Honduras, 2010..
        /// </summary>
        public static string perfiles_proyecto_4_li1 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_4_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto de 2 meses..
        /// </summary>
        public static string perfiles_proyecto_4_li2 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_4_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto BANK OF AMERICA.
        /// </summary>
        public static string perfiles_proyecto_5 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El liderar la transición estratégica, Costa Rica + Mex 2010..
        /// </summary>
        public static string perfiles_proyecto_5_li1 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_5_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de 9 meses..
        /// </summary>
        public static string perfiles_proyecto_5_li2 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_5_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto HSBC Panamá.
        /// </summary>
        public static string perfiles_proyecto_6 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rediseño del modelo de gestión del talento, con reorganizaciones (fortalecimiento) del área comercial movilizando más de 80 personas mensualmente..
        /// </summary>
        public static string perfiles_proyecto_6_li1 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_6_li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de 1 año..
        /// </summary>
        public static string perfiles_proyecto_6_li2 {
            get {
                return ResourceManager.GetString("perfiles_proyecto_6_li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process Innovation, o innovación de procesos, se refiere a la creación o mejora de procesos empresariales para aumentar la eficiencia, productividad y calidad de los productos o servicios ofrecidos. Implica reorganizar tareas, implementar nuevas tecnologías, mejorar la capacitación y eliminar procesos innecesarios para mejorar la satisfacción del cliente, reducir costos y mejorar la adaptabilidad al cambio de mercado. La innovación de procesos es importante para mantener la competitividad y sostenibilidad a [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string processInovation_descr {
            get {
                return ResourceManager.GetString("processInovation_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process Innovation.
        /// </summary>
        public static string processInovation_h1 {
            get {
                return ResourceManager.GetString("processInovation_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standar Execution Programs.
        /// </summary>
        public static string processInovation_h2_1 {
            get {
                return ResourceManager.GetString("processInovation_h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project Management Solutions.
        /// </summary>
        public static string processInovation_h2_2 {
            get {
                return ResourceManager.GetString("processInovation_h2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicator Model Design.
        /// </summary>
        public static string processInovation_h2_3 {
            get {
                return ResourceManager.GetString("processInovation_h2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance Alignment &amp; Strategy.
        /// </summary>
        public static string processInovation_h2_4 {
            get {
                return ResourceManager.GetString("processInovation_h2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Savings &amp; Costs Reduction Strategy.
        /// </summary>
        public static string processInovation_h2_5 {
            get {
                return ResourceManager.GetString("processInovation_h2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de mejora continua enfocados hacia la estandarización de conformidad con normas internacionales.
        /// </summary>
        public static string processInovation_p_1 {
            get {
                return ResourceManager.GetString("processInovation_p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metodología para la planeación, dirección y control de proyectos mediante un sistema de ejecución de conformidad con el PMI.
        /// </summary>
        public static string processInovation_p_2 {
            get {
                return ResourceManager.GetString("processInovation_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño e implementación de sistemas de información gerencial para la toma de decisiones.
        /// </summary>
        public static string processInovation_p_3 {
            get {
                return ResourceManager.GetString("processInovation_p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programas de administración del cambio para el alineamiento del desempeño y la estrategia.
        /// </summary>
        public static string processInovation_p_4 {
            get {
                return ResourceManager.GetString("processInovation_p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa para la generación de rentabilidad mediante la optimización de procesos, reducción de costos y mejora de eficiencias.
        /// </summary>
        public static string processInovation_p_5 {
            get {
                return ResourceManager.GetString("processInovation_p_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talent Management es el conjunto de prácticas y procesos utilizados por las organizaciones para atraer, desarrollar, motivar y retener a empleados altamente calificados y comprometidos que contribuyan significativamente al éxito de la empresa. Las empresas que implementan una estrategia efectiva de gestión del talento son más propensas a retener y atraer a los mejores talentos, mejorar el rendimiento general y mantenerse competitivas a largo plazo en un mercado cambiante..
        /// </summary>
        public static string talentManagement_descr {
            get {
                return ResourceManager.GetString("talentManagement_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talent Management.
        /// </summary>
        public static string talentManagement_h1 {
            get {
                return ResourceManager.GetString("talentManagement_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Executive Search.
        /// </summary>
        public static string talentManagement_h2_1 {
            get {
                return ResourceManager.GetString("talentManagement_h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 360 Perspective Analysis.
        /// </summary>
        public static string talentManagement_h2_2 {
            get {
                return ResourceManager.GetString("talentManagement_h2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competence Measurement System.
        /// </summary>
        public static string talentManagement_h2_3 {
            get {
                return ResourceManager.GetString("talentManagement_h2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leadership Aceleration Program.
        /// </summary>
        public static string talentManagement_h2_4 {
            get {
                return ResourceManager.GetString("talentManagement_h2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Five Steps For Performance.
        /// </summary>
        public static string talentManagement_h2_5 {
            get {
                return ResourceManager.GetString("talentManagement_h2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de reclutamiento basado en competencias e indicadores de gestión.
        /// </summary>
        public static string talentManagement_p {
            get {
                return ResourceManager.GetString("talentManagement_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de medición de la satisfacción laboral y de la opinión de públicos interesados para el cambio.
        /// </summary>
        public static string talentManagement_p_2 {
            get {
                return ResourceManager.GetString("talentManagement_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de evaluación para identificar brechas de competencias de una persona versus el puesto.
        /// </summary>
        public static string talentManagement_p_3 {
            get {
                return ResourceManager.GetString("talentManagement_p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asesoría personalizada en el desarrollo de competencias para mejorar el desempeño.
        /// </summary>
        public static string talentManagement_p_4 {
            get {
                return ResourceManager.GetString("talentManagement_p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa de entrenamiento compuesto por cinco niveles de ejecución del método SMART.
        /// </summary>
        public static string talentManagement_p_5 {
            get {
                return ResourceManager.GetString("talentManagement_p_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fundación de Adwise.
        /// </summary>
        public static string timeline_2006_h2 {
            get {
                return ResourceManager.GetString("timeline_2006_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2006.
        /// </summary>
        public static string timeline_2006_h3 {
            get {
                return ResourceManager.GetString("timeline_2006_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La firma comenzó en el 2006 con oficinas en Costa Rica y un enfoque en soluciones de capital humano para la región..
        /// </summary>
        public static string timeline_2006_text {
            get {
                return ResourceManager.GetString("timeline_2006_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ampliación de soluciones.
        /// </summary>
        public static string timeline_2008_h2 {
            get {
                return ResourceManager.GetString("timeline_2008_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2008.
        /// </summary>
        public static string timeline_2008_h3 {
            get {
                return ResourceManager.GetString("timeline_2008_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En 2008, la empresa comenzó a ofrecer nuevas soluciones en otras áreas de negocio, específicamente en el campo de la optimización de procesos. Abrió sus primeras oficinas fuera de Costa Rica en Panamá y Trinidad y Tobago, se implementó un entrenamiento de alto nivel para el SM JALEEL en Trinidad y Tobago, compartió otras iniciativas de coaching en República Dominicana..
        /// </summary>
        public static string timeline_2008_text {
            get {
                return ResourceManager.GetString("timeline_2008_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transnacionales en Centroamérica y el Caribe.
        /// </summary>
        public static string timeline_2009_h2 {
            get {
                return ResourceManager.GetString("timeline_2009_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2009.
        /// </summary>
        public static string timeline_2009_h3 {
            get {
                return ResourceManager.GetString("timeline_2009_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En 2009, la firma se centró en empresas transnacionales en Centroamérica y el Caribe y diseñó la estrategia que llevó a TETRA PAK Centroamérica &amp; Caribe a ganar el premio mundial «Market Region of the Year 2008»..
        /// </summary>
        public static string timeline_2009_text {
            get {
                return ResourceManager.GetString("timeline_2009_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevos consultores y directores.
        /// </summary>
        public static string timeline_2010_5_h2 {
            get {
                return ResourceManager.GetString("timeline_2010.5_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2010.
        /// </summary>
        public static string timeline_2010_5_h3 {
            get {
                return ResourceManager.GetString("timeline_2010.5_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La firma incorporó nuevos consultores y directores en 2010 y logró concluir un proyecto de optimización con ahorros significativos en la cadena de abastecimiento para TETRA PAK en Panamá..
        /// </summary>
        public static string timeline_2010_5_text {
            get {
                return ResourceManager.GetString("timeline_2010.5_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursal en Bogotá, Colombia.
        /// </summary>
        public static string timeline_2010_h2 {
            get {
                return ResourceManager.GetString("timeline_2010_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2010.
        /// </summary>
        public static string timeline_2010_h3 {
            get {
                return ResourceManager.GetString("timeline_2010_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En 2010, la firma abrió una sucursal en Bogotá, Colombia y se incorporó la división de calidad, desarrollando nuevas soluciones de negocio en cada una de sus áreas de especialización. También comenzó a trabajar con Scotiabank en Panamá y Costa Rica en proyectos de outsourcing y headhunting..
        /// </summary>
        public static string timeline_2010_text {
            get {
                return ResourceManager.GetString("timeline_2010_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca Adwise.
        /// </summary>
        public static string timeline_2011_h2 {
            get {
                return ResourceManager.GetString("timeline_2011_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2011.
        /// </summary>
        public static string timeline_2011_h3 {
            get {
                return ResourceManager.GetString("timeline_2011_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el 2011, la Firma comienza a operar bajo la marca ADWISE fortaleciendo y diversificando sus soluciones, de conformidad con las necesidades del mercado y expandiendo su presencia física hacia Centroamérica, Suramérica y el Caribe mediante oficinas de representación y un centro de operaciones comerciales en Miami Fl..
        /// </summary>
        public static string timeline_2011_text {
            get {
                return ResourceManager.GetString("timeline_2011_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consolidación de unidad de outsourcing.
        /// </summary>
        public static string timeline_2013_h2 {
            get {
                return ResourceManager.GetString("timeline_2013_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2013.
        /// </summary>
        public static string timeline_2013_h3 {
            get {
                return ResourceManager.GetString("timeline_2013_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el año 2013, ADWISE es adjudicada por Scotiabank Costa Rica para implementar exitosamente un proyecto de Outsourcing administrando más de 60 recursos para el banco y asume proyectos de Planillas Administradas para SCOTIABANK en Panamá y Costa Rica..
        /// </summary>
        public static string timeline_2013_text {
            get {
                return ResourceManager.GetString("timeline_2013_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casa Matriz.
        /// </summary>
        public static string timeline_2015_h2 {
            get {
                return ResourceManager.GetString("timeline_2015_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2015.
        /// </summary>
        public static string timeline_2015_h3 {
            get {
                return ResourceManager.GetString("timeline_2015_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A partir del año 2015, se reubica la Casa Matriz de la Firma en Ciudad de Panamá, ubicando su Expertise Delivery Center. En el corto y mediano plazo la firma continuará fortaleciendo y diversificando sus soluciones, de conformidad con las necesidades del mercado y expandiendo su presencia física hacia Centroamérica, Suramérica y el Caribe. Actualmente la Firma cuenta con socios en América Latina, Estados Unidos &amp; España..
        /// </summary>
        public static string timeline_2015_text {
            get {
                return ResourceManager.GetString("timeline_2015_text", resourceCulture);
            }
        }
    }
}
